import './globals.css';
import {Roboto} from 'next/font/google';
import {StoreProvider} from '@/stores/store-provider';
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata = {
  icon: 'favicon.ico',
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Layout root returns
 * @return {React.RootLayout} The layout root.
 */
export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
